# Generated by Django 3.1.2 on 2020-10-08 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('texts_list', models.CharField(max_length=12)),
                ('bin', models.IntegerField()),
                ('total', models.TextField()),
                ('data', models.DateField()),
            ],
        ),
    ]
